/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  dashboard: {
    Dashboard: () => import('#controllers/dashboard/dashboard_controller'),
    Places: () => import('#controllers/dashboard/places_controller'),
    Quartiers: () => import('#controllers/dashboard/quartiers_controller'),
    Reviews: () => import('#controllers/dashboard/reviews_controller'),
    Tags: () => import('#controllers/dashboard/tags_controller'),
  },
  Explorers: () => import('#controllers/explorers_controller'),
  Home: () => import('#controllers/home_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
  settings: {
    Profile: () => import('#controllers/settings/profile_controller'),
    Security: () => import('#controllers/settings/security_controller'),
  },
}
