/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  NewAccount: () => import(#controllers/dashboard/dashboard_controllerler'),
  Session: () => import('#controllers/session_controller'),
  dashboard: {
    Tags: () => import('#controllers/dashboard/tags_controller'),
    Dashboard: () => import('#controllers/dashboard/dashboard_controller'),
  },
}
