/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type PlaceTransformer from '#transformers/place_transformer'
import type QuartierTransformer from '#transformers/quartier_transformer'
import type ReviewTransformer from '#transformers/review_transformer'
import type TagTransformer from '#transformers/tag_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type Place = InferData<PlaceTransformer>
  export namespace Place {
    export type Variants = InferVariants<PlaceTransformer>
  }
  export type Quartier = InferData<QuartierTransformer>
  export namespace Quartier {
    export type Variants = InferVariants<QuartierTransformer>
  }
  export type Review = InferData<ReviewTransformer>
  export namespace Review {
    export type Variants = InferVariants<ReviewTransformer>
  }
  export type Tag = InferData<TagTransformer>
  export namespace Tag {
    export type Variants = InferVariants<TagTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
